=== endzix22/XML/ssaki.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="pl">
      XML Schema do pliku ssaki.
    </xs:documentation>
  </xs:annotation>
  
	<xs:element name="Ssaki">
	  <xs:complexType> 
		<xs:sequence>
		  <xs:element name="gatunki" >
			<xs:complexType>
				<xs:sequence>
					<xs:element name="ssak" type="ssak_typ" maxOccurs="6"/>
				</xs:sequence>
			</xs:complexType>
		  </xs:element>
		  <xs:element name="zagrozone_gatunki" type="zagrozone_gatunki_typ"/>
		  <xs:element name="Mammalia" type="Mammalia_typ"/>
		</xs:sequence>
	  </xs:complexType>
	</xs:element>
	
	<xs:attribute name="id">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:minExclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="nazwa" type="opisType"/>
	<xs:element name="zdjecie" type="zdjecieType"/>


	<xs:complexType name="ssak_typ">
		<xs:sequence>
			<xs:element ref="zdjecie" />
			<xs:element name="link" type="opisType"/>
			<xs:element name="dlugosc_zycia" type="plec_typ" maxOccurs="2"/>
			<xs:element name="wysokosc" type="plec_typ" maxOccurs="2"/>
		</xs:sequence>
		<xs:attribute ref="id"/>
		<xs:attribute ref="nazwa"/>
		<xs:attribute name="wystepowanie" type="kontynent_typ"/>
	</xs:complexType>
	
	<xs:complexType name="plec_typ">
		<xs:sequence>
			<xs:element name="samiec" type="unia"/>
			<xs:element name="samica" type="unia"/>
		</xs:sequence>
		<xs:attribute name="mieszkanie" type="opisType"/>
	</xs:complexType>

	<xs:simpleType name="unia">
		<xs:union memberTypes="liczba_typ wysokoscType"/>
	</xs:simpleType>

	<xs:simpleType name="wysokoscType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(.)+\ (cm)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="liczba_typ">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="2500"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:simpleType name="kontynent_typ">
		<xs:restriction base="xs:string">
		<xs:enumeration value="Azja"/>
		  <xs:enumeration value="Afryka"/>
		  <xs:enumeration value="Europa"/>
		  <xs:enumeration value="Ameryka Północna"/>
		  <xs:enumeration value="Ameryka Południowa"/>
		  <xs:enumeration value="Australia i Oceania"/>
		</xs:restriction>
	</xs:simpleType>



	<xs:complexType name="zagrozone_gatunki_typ">
		<xs:sequence>
			<xs:element ref="opis"/>
			<xs:element name="gatunek_lista" type="gatunek_listaType"/>
			<xs:element name="zwierze" type="zwierzeType"  maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="gatunek_listaType">
		<xs:list itemType="opisType"/>
	</xs:simpleType>

	<xs:element name="opis" type="opisType"/>

	<xs:simpleType name="opisType">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:group name="zwierze-GRUPA">
		<xs:sequence>
			<xs:element name="gatunek">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="zagrozony"/>
						<xs:enumeration value="wymarly"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:group>




	<xs:complexType name="zwierzeType">
		<xs:group ref="zwierze-GRUPA"/>
		<xs:attribute name="jakie" type="opisType"/>
		<xs:attribute ref="id"/>
		<xs:attribute name="czy_istnieje" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Mammalia_typ">
		<xs:all>
			<xs:element name="domena" type="opisType"/>
			<xs:element ref="opis"/>
			<xs:element ref="zdjecie" />
			<xs:element name="podtyp" type="opisType"/>
			<xs:element name="nadgromada" type="nadgromadaType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="zdjecieType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="src" type="srcType"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="srcType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(.)+\.(jpg)"/>
		</xs:restriction>
	</xs:simpleType>	

	<xs:simpleType name="nadgromadaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="czworonogie"/>
			<xs:enumeration value="dwunogie"/>
		</xs:restriction>
	</xs:simpleType>

	
</xs:schema>

=== endzix22/XML/ssaki.xml
<?xml version="1.0" encoding="utf-8"?>
<Ssaki xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ssaki.xsd">
	<gatunki>
		<ssak id="1" nazwa="Lew" wystepowanie="Afryka">
			<zdjecie src="lew.jpg">lew.jpg</zdjecie>
			<link>http://pl.wikipedia.org/lew</link>
			<dlugosc_zycia mieszkanie="na wolnosci">
				<samiec>31</samiec>
				<samica>34</samica>
			</dlugosc_zycia>
			<dlugosc_zycia mieszkanie="w niewoli">
				<samiec>25</samiec>
				<samica>30</samica>
			</dlugosc_zycia>
			<wysokosc>
				<samiec>120 cm</samiec>
				<samica>110 cm</samica>
			</wysokosc>
		</ssak>
		
		<ssak id="2" nazwa="Slon" wystepowanie="Afryka">
			<zdjecie src="lew.jpg">lew.jpg</zdjecie>
			<link>http://pl.wikipedia.org/lew</link>
			<dlugosc_zycia mieszkanie="na wolnosci">
				<samiec>32</samiec>
				<samica>60</samica>
			</dlugosc_zycia>
			<dlugosc_zycia mieszkanie="w niewoli">
				<samiec>65</samiec>
				<samica>65</samica>
			</dlugosc_zycia>
			<wysokosc>
			  <samiec>250 cm</samiec>
			  <samica>230 cm</samica>
			</wysokosc>
		</ssak>

		<ssak id="3" nazwa="Zajac" wystepowanie="Europa">
			<zdjecie src="lew.jpg">lew.jpg</zdjecie>
			<link>http://pl.wikipedia.org/lew</link>
			<dlugosc_zycia mieszkanie="na wolnosci">
				<samiec>4</samiec>
				<samica>5</samica>
			</dlugosc_zycia>
			<dlugosc_zycia mieszkanie="w niewoli">
				<samiec>8</samiec>
				<samica>10</samica>
			</dlugosc_zycia>
			<wysokosc>
			  <samiec>60 cm</samiec>
			  <samica>56 cm</samica>
			</wysokosc>
		</ssak>

		<ssak id="4" nazwa="Sarna" wystepowanie="Europa">
			<zdjecie src="lew.jpg">lew.jpg</zdjecie>
			<link>http://pl.wikipedia.org/sarna</link>
			<dlugosc_zycia mieszkanie="na wolnosci">
				<samiec>13</samiec>
				<samica>15</samica>
			</dlugosc_zycia>
			<dlugosc_zycia mieszkanie="w niewoli">
				<samiec>20</samiec>
				<samica>25</samica>
			</dlugosc_zycia>
			<wysokosc>
			  <samiec>70 cm</samiec>
			  <samica>67 cm</samica>
			</wysokosc>
		</ssak>
	</gatunki>
	
	<zagrozone_gatunki>
		<opis>
		gatunki zwierząt zaliczanych do gromady ssaków uznane przez Międzynarodową Unię Ochrony Przyrody i Jej Zasobów za zagrożone wyginięciem. W Czerwonej Księdze IUCN wyróżnione zostały trzy kategorie zagrożenia wyginięciem: krytycznie zagrożone (CR), zagrożone (EN) i narażone (VU), czyli podatne na wyginięcie w najbliższej przyszłości.
		</opis>
		<gatunek_lista>zagrozone CR EN narazone VU wymarle</gatunek_lista>
		<zwierze jakie="wol mindorski" id="1" czy_istnieje="false">
			<gatunek>zagrozony</gatunek>
		</zwierze>
		<zwierze jakie="Muriki polnocny" id="2" czy_istnieje="false">
			<gatunek>wymarly</gatunek>
		</zwierze>
		<zwierze jakie="Wilk rudy" id="3" czy_istnieje="true">
			<gatunek>zagrozony</gatunek>
		</zwierze>
		<zwierze jakie="Drzewniak stokowy" id="4" czy_istnieje="true">
			<gatunek>zagrozony</gatunek>
		</zwierze>
	</zagrozone_gatunki>
	
	<Mammalia>
		<domena>eukarionty</domena>
		<opis>
		Gromada stałocieplnych zwierząt z podtypu kręgowców.
Ssaki (Mammalia) – zwierzęta należące do kręgowców, charakteryzujące się głównie występowaniem gruczołów mlekowych u samic, zazwyczaj obecnością owłosienia (włosy lub futro; silnie zredukowane u gatunków wodnych, jak hipopotamy, u waleni całkowicie zanikają przed porodem lub w trakcie) oraz stałocieplnością (potocznie „ciepłokrwistość”). Ok 60% ssaków utrzymuje temperaturę w granicach 34–39 °C, 40% wykazuje zróżnicowaną jej zmienność[2]. Stałocieplność umożliwia aktywny tryb życia w różnych środowiskach – od mroźnych obszarów podbiegunowych do gorących tropików. Futro i tłuszcz pomagają uchronić się przed zimnem, a wydzielanie potu i szybki oddech pomagają pozbyć się nadmiernego ciepła. Znaczna zmienność temperatury ciała umożliwia im natomiast ograniczenie strat ciepła do otoczenia.
		</opis>
		
		<zdjecie src="ssaki.jpg">ssaki.jpg</zdjecie>
		<podtyp>kręgowce</podtyp>
		<nadgromada>czworonogie</nadgromada>
	
	</Mammalia>
</Ssaki>
